server:
  port: 19091

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service
  cloud:
    gateway:
#      netty:
#        dns:
#          resolve-using: default
      routes:  # Spring Cloud Gateway의 라우팅 설정
        # 아래 임시 데이터 참고해서 서비스 추가해주시면 됩니다.
        - id: delivery-service  # 라우트 식별자
          uri: http://localhost:19097
#          uri: lb://delivery-service    # 'delivery-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/v1/search-deliveries/**
#          filters:
#            - StripPrefix=1  # 👈 /api/v1 앞부분 잘라서 delivery-service에 전달
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버의 URL을 지정
    fetch-registry: true


logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG